const products = [
 {
    id: 1,
    name: 'iPhone 16',
    description: 'The latest iPhone with advanced features and sleek design.',
    price: 999.99,
    discount: 20,
    rating: 4.5,
    img: 'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/309692_0_ois5su.png',
    originalPrice: 1249.99,
    category: 'Mobile',
 },
  {
    id: 2,
    name: 'Google Pixel 9a 5G (8GB RAM, 256GB, Obsidian)',
    description: 'The latest iPhone with advanced features and sleek design.',
    price: 699.99,
    discount: 15,
    rating: 4.4,
    img: 'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/314881_0_fc5HPjUQpi.png?updatedAt=1758548561336?tr=w-400',
    originalPrice: 874.99,
    category: 'Mobile',
 },
  {
    id: 3,
    name: 'vivo T5X 5G (8GB RAM, 128GB, Cyber Green)',
    description: 'The latest iPhone with advanced features and sleek design.',
    price: 299.99,
    discount: 10,
    rating: 4.5,
    img:'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/322099_0_WkZit3AXJ.png?updatedAt=1773751667940?tr=w-400',
    originalPrice: 409.99,
    category: 'Mobile',
 },
  {
    id: 4,
    name: 'vivo V60e 5G (8GB RAM, 128GB, Elite Purple)',
    description: 'The latest iPhone with advanced features and sleek design.',
    price: 299.99,
    discount: 10,
    rating: 4.5,
    img:'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/319748_0_n8etvt416.png?updatedAt=1764156513270?tr=w-400',
    originalPrice: 409.99,
    category: 'Mobile',
 },
  {
    id: 5,
    name: 'vivo V60e 5G (8GB RAM, 128GB, Elite Purple)',
    description: 'The latest iPhone with advanced features and sleek design.',
    price: 299.99,
    discount: 10,
    rating: 4.5,
    img:'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/319748_0_n8etvt416.png?updatedAt=1764156513270?tr=w-400',
    originalPrice: 409.99,
    category: 'Mobile',
 },
  {
    id: 6,
    name: 'Apple MacBook Air (13.6 inch, M4, 16GB, 512GB, macOS, Silver)',
    description: 'The latest iPhone with advanced features and sleek design.',
    price: 299.99,
    discount: 10,
    rating: 4.5,
    img:'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/314072_0_hgsoe3.png',
    originalPrice: 107900.00,
    category: 'Laptop',
 },
 {
    id: 7,
    name: 'HP 15-fd0588TU Intel Core i5 13th Gen Thin & Light Laptop ',
    description: 'The latest iPhone with advanced features and sleek design.',
    price: 299.99,
    discount: 10,
    rating: 4.5,
    img:'https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/316006_0_kshltm.png?tr=w-600',
    originalPrice: 107900.00,
    category: 'Laptop',
 },
 {
  id: 8,
  name: 'Samsung 55 Inch Smart TV',
  description: 'Ultra HD Smart TV with vibrant display and smart features.',
  price: 699,
  discount: 20,
  rating: 4.6,
  img: "https://pngimg.com/uploads/tv/tv_PNG39248.png",
  originalPrice: 899,
  category: 'TV'
},
  {
    id: 10,
    name: "HP Laptop",
    description: "Thin & light laptop with high performance.",
    price: 899,
    discount: 10,
    rating: 4.5,
    img: "https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/318951_0_YosZGBihx.png?updatedAt=1758873945390",
    originalPrice: 999,
    category: "Laptop"
  },
   {
    id: 11,
    name: "ASUS Vivobook",
    description: "Thin & light laptop with high performance.",
    price: 899,
    discount: 10,
    rating: 4.5,
    img: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/315070_0_wo7p5kiLu.png?updatedAt=1763015534977?tr=w-640",
    originalPrice: 999,
    category: "Laptop"
  },
{
    id: 12,
    name: "SAMSUNG Galaxy Watch Ultra",
    description: "Thin & light laptop with high performance.",
    price: 899,
    discount: 10,
    rating: 4.5,
    img: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Wearable%20Devices/Images/316946_0_fmSmQ2JHk.png?updatedAt=1763650370270?tr=w-640",
    originalPrice: 999,
    category: "Laptop"
  },
{
    id: 13,
    name: "noise NoiseFit Mettle Smartwatch",
    description: "Thin & light laptop with high performance.",
    price: 899,
    
    rating: 4.5,
    img: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Wearable%20Devices/Images/275664_0_SaXUGcrq0.png?updatedAt=1760542416721?tr=w-640",
    originalPrice: 999,
    category: "Laptop"
  },


   
];


export default products;